sudo: required
dist: trusty

before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.6 main'
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.7 main'
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.8 main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y clang-3.6 clang-3.7 clang-3.8
  - sudo apt install gcc-6
  - sudo apt-get install libboost-all-dev

language: cpp

compiler:
  - clang
  - gcc

script:
  - make
