sudo: required
dist: trusty

before_install:
  - openssl aes-256-cbc -K $encrypted_84a53e325742_key -iv $encrypted_84a53e325742_iv -in deploy-key.enc -out deploy-key -d
  - sudo apt-get -q -y update
  - sudo apt-get install libboost-all-dev

language: cpp

compiler:
  - clang
  - gcc

script:
  - make
