---
- hosts: servers
  remote_user: root

  tasks:
  - name: ensure git is installed
    apt: name=git state=present

  - name: ensure server group exists
    group: name=server
  
  - name: ensure server user exists
    user: name=server group=server 

  - name: update repositories cache and install "libboost-all-dev" package
    apt: name=libboost-all-dev update_cache=yes

  - name: install g++
    apt: name=g++

  - name: install make
    apt: name=make

  - name: install obsidian-server systemd unit file
    template: src=obsidian-server.j2 dest=/etc/systemd/system/obsidian-server.service

  - name: create directory
    file: path=/opt/obsidian-server state=directory

  - name: checkout obsidian-server repo from github
    become: yes
    become_user: server
    git: repo=ssh://git@github.com/seanbollin/obsidian-server.git key_file=/home/server/.ssh/id_rsa accept_hostkey=yes dest=/home/server/obsidian-server

  - name: make clean 
    make: target=clean chdir=/home/server/obsidian-server

  - name: make
    make: chdir=/home/server/obsidian-server
    become: true
    become_user: server
  
  - name: place binary in final folder
    copy: src=/home/server/obsidian-server/obsidian-server dest=/usr/local/bin/obsidian-server owner=server group=server mode=0670 backup=yes

  - name: start server
    systemd: state=restarted name=obsidian-server
