---
- hosts: servers
  remote_user: root

  tasks:
  - name: ensure git is installed
    apt: name=git state=present

  - name: ensure server group exists
    group: name=server
  
  - name: ensure server user exists
    user: name=server group=server 

  - name: update repositories cache and install "libboost-all-dev" package
    apt: name=libboost-all-dev update_cache=yes

  - name: install make
    apt: make

  - name: create directory
    file: path=/opt/obsidian-server state=directory

  - name: checkout obsidian-server repo from github
    become: yes
    become_user: server
    git: repo=ssh://git@github.com/seanbollin/obsidian-server.git key_file=/home/server/.ssh/id_rsa accept_hostkey=yes dest=/home/server/obsidian-server

  - name: build default target
    make: chdir=/home/server/obsidian-server
