---
- hosts: servers
  remote_user: root

  tasks:
  - name: ensure git is installed
    apt: name=git state=present

  - name: ensure server group exists
    group: name=server
  
  - name: ensure server user exists
    user: name=server group=server 

  - name: update repositories cache and install "libboost-all-dev" package
    apt: name=libboost-all-dev update_cache=yes

  - name: create directory
    file: path=/opt/obsidian-server state=directory

  - name: copy obsidian-server binary
    copy: src=../obsidian-server dest=/opt/obsidian-server/obsidian-server owner=server group=server mode=0700 force=yes 
